### PR TITLE
Ensure we are counting duplicates correctly. Fixes #19

### LINKED ISSUE #19: Duplicate count is still incorrect
It turns out that the Bugzilla `history` field only counts changes to the initial bug, and so many see-also links are being missed by the dupe counts (as they are not changes; they are part of the initial bug report, so the history field doesn't include them).

To fix this we'll need to also fetch the `see-also` field, and the `creation_time` field, and count those that were not in the history with that date.

### PR DESCRIPTION
**Pull request by wisniewskit**
Note that in addition to the history issue mentioned in #19, this also includes the fix mentioned [here](https://github.com/past/tsci/issues/8#issuecomment-495811151), as well as a drive-by fix to ensure that the correct final number is output in the spreadsheet (the count of webcompat.com issues in the see-also fields, not the count of the bugzilla bugs with those see-alsos).

### CODE REVIEW

File: bugs.js [hunk 1]
```diff
@@ -192,6 +192,45 @@ const getWebcompat = async (website, githubKey, minDate, maxDate) => {
     };
 }
 
+/**
+ * Returns the list of see-also links for a given Bugzilla bug.
+ *
+ * @param {*} a Bugzilla bug's metadata including its creation_time,
+              see_also, and history fields.
+ * returns a Map of the bug's see-also links mapped to the date they were added.
```
Comment (past) [inline bugs.js]: Typo: @returns

File: bugs.js [hunk 2]
```diff
@@ -192,6 +192,45 @@ const getWebcompat = async (website, githubKey, minDate, maxDate) => {
...
+ */
+
```
Comment (past) [inline bugs.js]: Nit: remove empty line

File: bugs.js [hunk 3]
```diff
@@ -192,6 +192,45 @@ const getWebcompat = async (website, githubKey, minDate, maxDate) => {
...
+        const date = new Date(when);
+        for (const {added, removed, field_name} of changes) {
+            if (field_name === "see_also") {
+                if (removed) {
+                    for (const url of removed.split(",")) {
+                        seeAlsos.delete(url.trim());
+                    }
+                }
+                if (added) {
+                    for (const url of removed.split(",")) {
```
Comment (past) [inline bugs.js]: This should be `added` instead of `removed`, right?

File: bugs.js [hunk 4]
```diff
@@ -192,6 +192,45 @@ const getWebcompat = async (website, githubKey, minDate, maxDate) => {
...
+    const date = new Date(bug.creation_time);
+    for (const initial of bug.see_also) {
+        for (const url of initial.split(",")) {
+            seeAlsos.set(url.trim(), date);
+        }
+    }
+
+    for (const {when, changes} of bug.history) {
+        const date = new Date(when);
+        for (const {added, removed, field_name} of changes) {
```
Comment (past) [inline bugs.js]: What is the enumeration order for changes? Specifically, if I create a bug with a see_also and then modify it to remove and then add back the same value, will it eventually be present in this map?

File: bugs.js [hunk 5]
```diff
@@ -261,17 +295,21 @@ const getDuplicates = async (website, bugzillaKey, githubKey, minDate, maxDate)
...
     const octokit = getOctokitInstance(githubKey);
     for (const [query, ghToBzMap] of searches) {
-        const milestoneSearch = `https://api.github.com/search/issues?per_page=100&q=${query}`;
+        const milestoneSearch = `https://api.github.com/search/issues?q=${query}`;
         const results = await getAllGitHubResultsFor(octokit.request, {url: milestoneSearch});
         for (const item of results) {
             const bzId = ghToBzMap.get(item.number);
             if (bzId && item.milestone.title === "duplicate") {
                 dupedBzIds.add(bzId);
+                ++dupeCount;
```
Comment (past) [inline bugs.js]: I have to admit that I am confused by this dupe counting. I trust you have thought this through, but could you explain for my own education why dupeCount will not double count webcompat issues in the see_also fields that we have visited in earlier iterations of the loop?

File: bugs.js (hunk 3 above)
Comment (wisniewskit) [reply bugs.js]: Um, yes :)

File: bugs.js (hunk 4 above)
Comment (wisniewskit) [reply bugs.js]: From what I can tell, the order of the `history` array is based on the order of historical operations, so if we remove a URL, and then later add it back, we should see a "remove" followed by an "add" in the `history` array. And if we simply remove it, then the last change we will have in the array is a "remove" for that URL.

But if we're uncomfortable with the presumption that the order of the array-items won't be stable, then I don't mind adding a call to sort it by each changes' related date first.

File: bugs.js (hunk 5 above)
Comment (wisniewskit) [reply bugs.js]: Actually, it might very well do so. It's possible that more than one Bugzilla bug will see-also back to the same github/wc issue, and that would "double count" it. If that's not what we want, then I can ensure that each github issue is only counted once.

File: bugs.js (hunk 4 above)
Comment (wisniewskit) [reply bugs.js]: Actually, I might as well sort it anyway just in case, since it's a trivial change.

File: bugs.js (hunk 5 above)
Comment (past) [reply bugs.js]: I think counting them once would be best. We are essentially trying to pick up the signal of user annoyance, but without amplifying it through our triage artifacts in the process.

Comment (wisniewskit) [reply bugs.js]: Sure, I'll adjust that in my upcoming diff to this patch.
